services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=traveler
      - MONGO_INITDB_ROOT_PASSWORD=travelerpassword
      - MONGO_INITDB_DATABASE=traveler
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
  web:
    build: .
    volumes:
      - .:/app
      # comment next line to exclude the node_modules
      - /app/node_modules
      # comment next line to exclude the docker configuration
      # - /app/docker
    ports:
      - "3001:3001"
      - "3002:3002"
      # - "3443:3443"
    restart: unless-stopped
    command: nodemon app.js
    environment:
      - TRAVELER_CONFIG_REL_PATH=docker
      - DEBUG=traveler:*
      - DEBUG_COLORS=true
    depends_on:
      # - mongo
      mongo:
       condition: service_healthy
  ldap-service:
    image: osixia/openldap:1.2.1
    command: --copy-service
    volumes:
      - ./seed:/container/service/slapd/assets/config/bootstrap/ldif/custom
    # ports:
    #   - 389:389
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    restart: unless-stopped
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
    depends_on:
      - ldap-service