#!/bin/bash

MY_DIR=`dirname $0`
CUR_DIR=`pwd`
cd $MY_DIR
MY_DIR=`pwd` 
cd $CUR_DIR 

source $MY_DIR/../../setup.sh

TRAVELERD_CONFIGURATION=$TRAVELER_INSTALL_ETC_DIR/travelerd_configuration.sh
if [ ! -f $TRAVELERD_CONFIGURATION ]; then 
    >&2 echo "$TRAVELERD_CONFIGURATION is not defined"
    >&2 echo "Please use the default file to configure it."
    exit 1
fi

source $TRAVELERD_CONFIGURATION

ERR_RED='\033[0;31m'
ERR_END='\033[0m\n'

printErr(){
    printf "${ERR_RED}${1}${ERR_END}"
}

start(){
    if [ -f $TRAVELERD_PID_FILE ]; then
	>&2 printErr "ERROR: Make sure the travelerd is not running. A pid file exists: $TRAVELERD_PID_FILE"
	exit 1
    fi

    $FOREVER_BIN/forever start --sourceDIR $TRAVELERD_SOURCE_DIR\
	--workingDir $TRAVELERD_WORKING_DIR \
	-p $TRAVELERD_FOREVER_PATH \
	--pidFile $TRAVELERD_PID_FILE \
	-l $TRAVELERD_LOG \
	-o $TRAVELERD_OUT \
	-e $TRAVELERD_ERR \
	--append \
	--killSignal=$TRAVELER_KILSIG \
	$TRAVELER_APP_DIR
}

stop(){
    if [ -f $TRAVELERD_PID_FILE ]; then
	$FOREVER_BIN/forever stop `cat $TRAVELERD_PID_FILE`
    else
	>&2 printErr "ERROR: Cannot stop process. No pid file exists: $TRAVELERD_PID_FILE"
	exit 1
    fi
}

restart(){
    stop
    start
}

status(){
    if [ -f $TRAVELERD_PID_FILE ]; then
	echo "Status for travelerd pid: `cat $TRAVELERD_PID_FILE`"
	$FOREVER_BIN/forever list
    else
	>&2 printErr "ERROR: Cannot find the pid file: ${TRAVELERD_PID_FILE}"
	echo "Output for forever list: "
	$FOREVER_BIN/forever list 
	exit 1
    fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac