#!/bin/bash

MY_DIR=`dirname $0`
CUR_DIR=`pwd`
cd $MY_DIR
MY_DIR=`pwd` 
cd $CUR_DIR 

source $MY_DIR/../../setup.sh

TRAVELERD_CONFIGURATION=$TRAVELER_INSTALL_ETC_DIR/travelerd_configuration.sh
if [ ! -f $TRAVELERD_CONFIGURATION ]; then 
    >&2 echo "$TRAVELERD_CONFIGURATION is not defined"
    >&2 echo "Please use the default file to configure it."
    exit 1
fi

source $TRAVELERD_CONFIGURATION

start(){        
    pm2 start $TRAVELER_APP_DIR --name traveler
}

stop(){
    pm2 stop $TRAVELER_APP_DIR
}

restart(){
    stop
    start
}

status(){
    pm2 status $TRAVELER_APP_DIR
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
    ;;
esac